[project]
name = "ceda-download-tool"
authors = [{name="Muhammad Mohsin", email="muhammad.mohsin@stfc.ac.uk"},]
version = "0.1.4"
description = "Download tool to install datasets"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.47",
    "bs4>=0.0.2",
    "cdsapi>=0.7.7",
    "ipykernel>=6.30.1",
    "moto[all,ec2,s3]>=5.1.21",
    "mypy-boto3-s3>=1.42.37",
    "paramiko>=4.0.0",
    "pytest-httpserver>=1.1.5",
]

[project.optional-dependencies]
tests = [
    "pyftpdlib>=2.2.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "requests-mock>=1.12.1",
    "ruff>=0.15.1",
    "moto[all,ec2,s3]>=5.1.21",
    "pre-commit>=4.5.1",
    "flask>=3.1.3",
    "flask-cors>=6.0.2",
]

[tool.ruff]
lint.select = ["E", "F", "I"]
line-length = 120
exclude = [
    "notebooks"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[build-system]
requires = ["uv_build >= 0.10.0, <0.11.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = ["ceda_download_tool"]

[tool.uv.build-backend]
module-name = "ceda_download_tool"
module-root = ""

[project.scripts]
ceda-download-tool = "ceda_download_tool.cli.main:main"
cdtool = "ceda_download_tool.cli.main:main"
