[project]
name = "dft"
version = "0.1.0"
description = "data federation tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["beautifulsoup4>=4.14.3", "cdsapi>=0.7.7", "ipykernel>=6.30.1"]

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
