from auth import TokenAuth
from session import create_session
from downloader import Downloader


url = "https://dap.ceda.ac.uk/badc/quest/data/qgsi/wp_d1_climate_scenarios/00README_catalogue_and_licence.txt?download=1"

auth = TokenAuth("eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4ZjhmaUpyaUtDY3hmaHhzdU5vazVEekdJdFZ4amhhTWNJa05ZX2U4MnhJIn0.eyJleHAiOjE3Njc5NTkzOTUsImlhdCI6MTc2NzcwMDE5NSwianRpIjoiNTFjMTNkZGEtZTJiMC00NjA3LThlMjYtOWE0MTU5ZDMwNGRiIiwiaXNzIjoiaHR0cHM6Ly9hY2NvdW50cy5jZWRhLmFjLnVrL3JlYWxtcy9jZWRhIiwic3ViIjoiODAwYjI5MmEtNzUzMC00YjM4LWJlZDEtZmM4Mzk5NmYzNWFmIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic2VydmljZXMtcG9ydGFsLWNlZGEtYWMtdWsiLCJzZXNzaW9uX3N0YXRlIjoiZmFlNDlmMTAtZmE5Yi00YzQxLTkzY2UtODdlNmQ0ZTQzNjVkIiwiYWNyIjoiMSIsInNjb3BlIjoiZW1haWwgb3BlbmlkIHByb2ZpbGUgZ3JvdXBfbWVtYmVyc2hpcCIsInNpZCI6ImZhZTQ5ZjEwLWZhOWItNGM0MS05M2NlLTg3ZTZkNGU0MzY1ZCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiTXVoYW1tYWQgTW9oc2luIiwicHJlZmVycmVkX3VzZXJuYW1lIjoibXRyNDY1ODUiLCJnaXZlbl9uYW1lIjoiTXVoYW1tYWQiLCJmYW1pbHlfbmFtZSI6Ik1vaHNpbiIsImVtYWlsIjoibXVoYW1tYWQubW9oc2luQHN0ZmMuYWMudWsifQ.dGgpPHPfet1jXreVDdemb0mRgNaltmDCHpEnClgyRgZg2mleccxhTXcdUKoN-Rz4x9Jylb4F0O6Lgk_jbu7r6g0zw5GIWnbJKlSz0rbmvmiPb7f2GkIygOlmf_XWr6DeEazk4eLrJv5GHRyXMTq5KpHWfBOqHVRln2BjnsC6yWpUgsXzH-epe1Rj_6ZE193TS3_0P5MmiE4Z4_ROu5t-Vo3xHhhbCCoEIIn4VhXPfzqWgC7Iev80IOvb5LP-J4eeuobszrK12W4Y0plRBbtxoTPAEeDbLnTdk_i2vUM4AOM1qS-ldYNYSil_gqU-hy_JF76K56R-o2a5fWV-UIU3wA")
session = create_session(30)
session.headers.update(auth.headers())

download = Downloader(session, url)

print(download.download(url))

